import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Shubham',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Aniket',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Beetroot Seeds',
      category: 'Seeds',
      image: '/images/s1.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'A root vegetable packed with Fibre , Manganese , Folate and Vitamin C is the Beetroot. Also known as table beet, garden beet, red beet, or dinner beet,has a vibrant, dark crimson which is often used as a natural colouring agent in various food items. If you eat your beets, it will take care of all your iron needs and also make your skin healthy.',
    },
    {
      name: 'Bittergourd Seeds (Green Long)',
      category: 'Seeds',
      image: '/images/s2.jpg',
      price: 73,
      countInStock: 0,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 2,
      description:
        'Bitter Gourd, commonly known as Karela in India is a unique tropical vine grown for its edible vegetable. The Bitter Gourd contains high amounts of fibre, phosphorous, and Vitamins C, B1, B2, and B3. Although not a crowd favourite, it surely has a cult following owing to its numerous health benefits',
    },
    {
      name: 'Black Brinjal Seeds (Round)',
      category: 'Seeds',
      image: '/images/s3.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'The Brinjal, also known as Aubergine or Eggplant, is a nutrient dense, perennial vegetable that is widely eaten in most Indian households. Brinjals love the warmth and grows well under bright sun and a well-drained soil.',
    },
    {
      name: 'Brocoli Seeds',
      category: 'Seeds',
      image: '/images/s4.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'Eat your greens – is where broccoli takes the cake. A cruciferous vegetable belonging to the Cabbage family, it doesn’t get greener and healthier than this. This nutrient dense superfood is loaded with Calcium, Vitamin C, Antioxidants, fibre, and Folate. Growing it in homes organically makes it all the better and tastier.',
    },
    {
      name: 'Green Capsicum',
      category: 'Seeds',
      image: '/images/s5.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'capsicum plants, which are under the genus of pepper plants, are not only popular for their health benefits, but are also popular for their medicinal properties. Capsicum is one of the vegetables that are a staple in the Indian pantries. The nutritional benefits of Capsicum are owing to the quantities of vitamin A, vitamin C, vitamin E, dietary fibre, vitamin B6, foliate and many more.',
    },
    {
      name: 'Red Capsicum',
      category: 'Seeds',
      image: '/images/s6.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'Red capsicum, also known as red bell pepper or sweet pepper (Capsicum annual), is becoming popular in urban India. It can be stuffed and cooked or sliced in salads. Red capsicum plants require more care and attention than most other vegetable crops to get proper yield. The plant needs daily 6 to 8 hours of direct sunlight when grown in winter.',
    },
    {
      name: 'Yellow Capsicum',
      category: 'Seeds',
      image: '/images/s7.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'yellow capsicum, also known as yellow bell pepper or sweet pepper (Capsicum annual), is becoming popular in urban India. It can be stuffed and cooked or sliced in salads. Yellow capsicum plants require more care and attention than most other vegetable crops to get proper yield. The plant needs daily 6 to 8 hours of direct sunlight when grown in winter.',
    },
    {
      name: 'carrot seeds',
      category: 'Seeds',
      image: '/images/s8.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'Nantes carrots are shorter, averaging 15 centimetres in length and have blunt and rounded ends with a beautiful orange colour. This carrot variety is crunchy, mildly sweet, and excellent to be had raw. Its name is based on the French city of Nantes and is the preferred carrot pf choice for carrot cake.',
    },
    {
      name: 'cauliflower seeds',
      category: 'Seeds',
      image: '/images/s9.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'Nantes carrots are shorter, averaging 15 centimetres in length and have blunt and rounded ends with a beautiful orange colour. This carrot variety is crunchy, mildly sweet, and excellent to be had raw. Its name is based on the French city of Nantes and is the preferred carrot pf choice for carrot cake.',
    },
    {
      name: 'Cucumber seeds',
      category: 'Seeds',
      image: '/images/s10.jpg',
      price: 73,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'Green cucumbers are a popular variety of spined cucumbers that are consumed as salads in every Indian home. Packed with vitamins and minerals, they are a great option for cooling down the body and increasing hydration owing to its water content. Excellent diet food option, these members of the watermelon family have good fibre content.',
    },
    {
      name: 'Green chilli',
      category: 'Seeds',
      image: '/images/s11.jpg',
      price: 73,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'Indian cuisine is synonymous with the use of chilli and it is a pantry staple in every Indian household. One of the easiest and most rewarding plants to grow for any food grower, the green chilli is an essential in every kitchen garden. Add them to curries, make a spice mix or pickle them, they taste good in all forms and are a great source of Vitamin A.',
    },
    {
      name: 'Lady finger',
      category: 'Seeds',
      image: '/images/s12.jpg',
      price: 73,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'Among the things that add allure to the Okra is that its benefits include the high content of magnesium, fibre, antioxidants, and vitamins. Okra is had in diets because it keeps you full longer owing to the fibre content, improves digestion and the vital nutrients improve immunity. Okra is called bhindi in Hindi.',
    },
    {
      name: 'Lettuce seeds',
      category: 'Seeds',
      image: '/images/s13.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'Put it in a burger or a sandwich or in a salad or make the famous south-east Asian lettuce cups this versatile vegetable is a favourite in all forms. This Crunchy and crisp green vegetable is loved by kids and grownups alike. Iceberg Lettuce is an annual plant belonging to the Asteraceae family and is loaded with Vitamin C and Vitamin K. It’s also easy to store after harvesting.',
    },
    {
      name: 'Tomato seeds',
      category: 'Seeds',
      image: '/images/s14.jpg',
      price: 88,
      countInStock: 10,
      brand: 'PYRAMID',
      rating: 4.5,
      numReviews: 10,
      description:
        'A staple in most of our households, the Tomato is a fragrant, edible berry of the Tomato plant that is packed with Vitamin C, Fibre, Vitamin A,Calcium and many other important antioxidants. Put it in curries, make soups, sauces or eat it raw, its tasty in all forms. Add a tangy and fresh flavour and a lot of nutrition to your food with a few tomatoes!',
    },

    {
      name: 'Bio-Organic G-5 - 2Kg',
      category: 'Organic-Fertilizer',
      image: '/images/or1.jpg',
      price: 300,
      countInStock: 10,
      brand: 'UGAAO',
      rating: 4.5,
      numReviews: 10,
      description:
        'The Bio-Organic granules help in promoting healthy growth of lawns, trees, shrubs and flowers. It is granular application fertilizer which enriches the soil and provides nutrients to the plant. It is applied directly to the soil at the rate of 25 gm per plant. It can be used for both indoor and outdoor plants.',
    },
    {
      name: 'Gardenia Cow Manure - 5 Kg',
      category: 'Organic-Fertilizer',
      image: '/images/or2.jpg',
      price: 399,
      countInStock: 10,
      brand: 'UGAAO',
      rating: 4.5,
      numReviews: 10,
      description:
        'Gardenia Cow Manure is an excellent fertilizer highly rich with organic matter and helps to improve aeration and break up compact soils. It is developed from composted cow dung of the Indian Desi cow and is incredibly rich with beneficial bacteria that convert soil nutrients into readily available forms for the tender plant.',
    },
    {
      name: 'K-Up Organic Potash 100ml',
      category: 'Organic-Fertilizer',
      image: '/images/or3.jpg',
      price: 199,
      countInStock: 10,
      brand: 'UGAAO',
      rating: 4.5,
      numReviews: 10,
      description:
        'K-UP when sprayed on plant or drenched near roots seedlings will start growing into a small plant. At this stage expose the seedlings to more & more sunlight for leaf growth.',
    },
    {
      name: 'Gardenia Organic manure 1-kg',
      category: 'Organic-Fertilizer',
      image: '/images/or4.jpg',
      price: 199,
      countInStock: 10,
      brand: 'UGAAO',
      rating: 4.5,
      numReviews: 10,
      description:
        'Gardenia Organic Manure provides the best nutrition for all types of plants and promotes vigorous growth. It is perfectly aged in compost pits before packaging and is plush with nutrients like Nitrogen but also provide an ideal growing option for plants and leafy vegetables. Mix it with garden soil in equal quntities or as advised for the best growing medium.',
    },
    {
      name: 'Ugaoo Plant Fertilizer Pellet - 1 Kg',
      category: 'Organic-Fertilizer',
      image: '/images/or5.jpg',
      price: 245,
      countInStock: 10,
      brand: 'UGAAO',
      rating: 4.5,
      numReviews: 10,
      description:
        'Made of organic poultry litter, the plant pellet fertilizer breathes life into the soil by adding in organic matter. It improves moisture retention and promotes the growth of beneficial microbes. It contains other micronutrients and NPK elements that enriches the soil without burning the roots. The pelleted form makes for easy application.',
    },
    {
      name: 'Vermicompost - 1 Kg',
      category: 'Organic-Fertilizer',
      image: '/images/or6.jpg',
      price: 199,
      countInStock: 10,
      brand: 'UGAAO',
      rating: 4.5,
      numReviews: 10,
      description:
        'Vermicompost is made by breaking down the organic material through the use of worms. Vermicompost improves biological, chemical, and physical properties of the soil. The worms break down soil and organic matter, so the nutrients are immediately available to plants. Vermicompost enhances plant growth, suppresses disease in plants, increases porosity and microbial activity in soil, and improves water retention and aeration.',
    },

    {
      name: 'Calcium Nitrate - 10 KG',
      category: 'Fertilizer',
      image: '/images/f1.png',
      price: 520,
      countInStock: 10,
      brand: 'ABTEC',
      rating: 4.5,
      numReviews: 10,
      description:
        'Calcium is an important secondary nutrient for the growth of plants. Calcium Nitrate is an excellent source of calcium for crops.In case of Calcium deficiency, and in acidic soils. It has a significant effect on crop growth, production as well quality.It enhances the quality and prolonged shelf life of the produce in most of the crops.It helps in the formation of new branches in plants, flowering and fruit development, and helps to prevent fruit drop',
    },

    {
      name: 'ABTEC Bio Potash',
      category: 'Fertilizer',
      image: '/images/bio-potash.jpg',
      price: 124,
      countInStock: 10,
      brand: 'ABTEC',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Fertilizer',
    },
    {
      name: 'Urea Phosphate (17:44:0) - 5 Kg',
      category: 'Fertilizer',
      image: '/images/f3.jpg',
      price: 420,
      countInStock: 10,
      brand: 'ABTEC',
      rating: 4.5,
      numReviews: 10,
      description:
        'Urea Phosphate (17-44-0): Completely soluble in water. Good source of useful nitrogen and phosphorus. Acidic nature. Valid and farmers-friendly price.',
    },
    {
      name: 'Potassium Nitrate (13-0-45) - 5 KG',
      category: 'Fertilizer',
      image: '/images/f2.jpg',
      price: 565,
      countInStock: 10,
      brand: 'ABTEC',
      rating: 4.5,
      numReviews: 10,
      description:
        'Moisture percent by weight, maximum – 0.5 Total Nitrogen (All in Nitrate form) percent by weight, minimum – 13.0 Water Soluble Potash (as K2O) percent by weight, minimum – 45.0 Sodium (as Na) (On dry basis) cent by weight, minimum – 1.0 Total chloride as Cl (On dry basis) percent by weight, maximum – 1.5 Matter insoluble in water percent by weight, maximum – 0.5',
    },
    {
      name: 'Agrovit fertilizer',
      category: 'Fertilizer',
      image: '/images/f4.jpg',
      price: 160,
      countInStock: 10,
      brand: 'ABTEC',
      rating: 4.5,
      numReviews: 10,
      description:
        'Agrovit is an Agricultural Wetting Agent. It is safe and an excellent wetting agent which improves wetting, spreading, sticking quality and enhance effectiveness of pesticidant spray.',
    },
    {
      name: 'Humacid - 1Ltr',
      category: 'Fertilizer',
      image: '/images/f5.jpg',
      price: 706,
      countInStock: 10,
      brand: 'ABTEC',
      rating: 4.5,
      numReviews: 10,
      description:
        'Humacid gives plants the nutrients they need to develop a lush foliage, abundant growth and high yields. It is mixed with a portion of 1-2 ml with 1 litre of water and applied via spraying. Plants can also be treated with drip irrigation to ensure a steady supply of nutrients. Can be applied to both indoor and outdoor plants.',
    },
    {
      name: 'Ugaoo Plant Fertilizer Pelletes - 1 Kg',
      category: 'Fertilizer',
      image: '/images/f6.jpg',
      price: 245,
      countInStock: 10,
      brand: 'ABTEC',
      rating: 4.5,
      numReviews: 10,
      description:
        'Made of organic poultry litter, the plant pellet fertilizer breathes life into the soil by adding in organic matter. It improves moisture retention and promotes the growth of beneficial microbes. It contains other micronutrients and NPK elements that enriches the soil without burning the roots. The pelleted form makes for easy application.',
    },
    {
      name: 'MULTIFEED (NPK 19:19:19) - 1 Kg',
      category: 'Fertilizer',
      image: '/images/f8.jpg',
      price: 190,
      countInStock: 10,
      brand: 'ABTEC',
      rating: 4.5,
      numReviews: 10,
      description:
        'N-P-K are macro nutrients plants need primarily. MULTIFEED is a water soluble fertilizer that can provide these marco nutrients easily and has the potential to fulfill any deficiency of one or all three major plant nutrients. Its use minimizes the need of synthetic fertilizers that are harmful to the environment.',
    },
  ],
};
export default data;